### ISSUE TITLE
Ideas for index pages of docs

### ISSUE THREAD

**Issue by Priyansi** [pytorch-ignite/pytorch-ignite.ai#20]
The index page of posts/ is automatically generated with an image, preview text and titles of the available blog posts. However, there is nothing like this for docs and we have to manually list down all the topics. Any ideas and suggestions on how to display various topics on the index pages will be appreciated!

Ideas List:
- Grid like structure - @trsvchn 
- Tag wise filtering of topics (for ex- computer vision, nlp, etc)

**Comment by ydcjeff** [comment]
Index pages has been implemented and tag filtering is tracked in #62
