### ISSUE TITLE
Replace "Introduction to PyTorch-Ignite" in the red bar by a link to the latest release

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/pytorch-ignite.ai#35]
Let's replace 

<img width="858" alt="Screen Shot 2021-08-03 at 10 16 15" src="https://user-images.githubusercontent.com/2459423/127982156-a70ca486-1498-41e2-8fcf-25d42a3e9b5d.png">

with a text like "Latest release: v0.4.6" and the link to the latest release.

**Comment by ydcjeff** [comment]
Link to GitHub release or blog post?

**Comment by vfdev-5** [comment]
To https://github.com/pytorch/ignite/releases/latest

**Comment by vfdev-5** [comment]
@ydcjeff should we update the title every time the new release appears ?

**Comment by ydcjeff** [comment]
Yes, we need to update.
