### ISSUE TITLE
Code cell font size issues

### ISSUE THREAD

**Issue by sdesrozis** [pytorch-ignite/pytorch-ignite.ai#54]
Using iOS safari, some code cells rendering problems appear. The font size seems not coherent.

Some screenshots below 

![image](https://user-images.githubusercontent.com/10013598/131786191-208df25d-c2ed-41e0-8b78-652764d119a6.png)

![image](https://user-images.githubusercontent.com/10013598/131786238-af7e559c-d602-467d-aad0-473c12a5c81e.png)

![image](https://user-images.githubusercontent.com/10013598/131786250-7ac1e263-12cd-4ada-bd55-175062a3cfc1.png)

**Comment by vfdev-5** [comment]
@sdesrozis can you check on another browser if this also happens ?

**Comment by sdesrozis** [comment]
> @sdesrozis can you check on another browser if this also happens ?

Same issue using Chrome, Firefox and Safari on iOS 14.7.1 iPhone XS Max

**Comment by ydcjeff** [comment]
@sdesrozis can you kindly check code blocks in  https://deploy-preview-78--pytorch-ignite.netlify.app/blog/introduction/ display correctly?

**Comment by sdesrozis** [comment]
> @sdesrozis can you kindly check code blocks in  https://deploy-preview-78--pytorch-ignite.netlify.app/blog/introduction/ display correctly?

@ydcjeff Everything looks pretty good. The rendering is very elegant and I didn't figure out any problem.
